name: flutter_fortune_wheel
description: An easy-to-use and customizable wheel of fortune for Flutter on all platforms.
version: 0.0.9
homepage: https://github.com/kevlatus/flutter_fortune_wheel
repository: https://github.com/kevlatus/flutter_fortune_wheel
documentation: https://github.com/kevlatus/flutter_fortune_wheel#readme

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^1.2.5
  flutter_hooks: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
